### ISSUE TITLE
Obsoleting .NET FoDUploader

### ISSUE THREAD

**Issue by mtgibbs** [ryancblack/FoDUploader#19]
As of September, the HPFOD public repositories will begin migration to a new organization.  This Uploader has been marked for deprecation and will no longer be supported by the Fortify development staff.  I will gladly transfer ownership to anyone who wants to keep and maintain it.

**Comment by ryancblack** [comment]
I'm happy to take this back in if I have access to API documentation to update.

It's fun to have a variety of coding projects and I think it, even if unsupported, may still be useful to the community.

**Comment by mtgibbs** [comment]
Everyone has access to the FoD API documentation via swagger.

https://api.ams.fortify.com/swagger/ui/index

**Comment by mtgibbs** [comment]
@ryancblack We've removed the links from the FoD portal now, so I'm good to transfer this to you.  You'll need to delete your fork because it's telling me that you already have a repo of the same name.

**Comment by ryancblack** [comment]
Thanks @mtgibbs, I've deleted my fork.

**Comment by mtgibbs** [comment]
Alright!  It has to bounce through my account for a second.  So give it a few minutes to make its trip around to you.
