### ISSUE TITLE
[enhancement] FodUploader.exe tool should support a "polling_interval" parameter

### ISSUE THREAD

**Issue by ioparin** [ryancblack/FoDUploader#5]
An enhancement one.

Per Sotack, Tim: 

the order  of parameters for a uploader tool  is the same

to use the new functionality you need to use a new named parameter

called polling_interval

 java -ja FodUpload.jar username password url payload_location -polling_interval:10

where the interval is in minutes

so it can go anywhere after the required parameters

the polling_interval indicates how frequently we poll the api for status updates

it will keep polling until it receives a message indicating completion or failure or cancellation

If it completes it will give pass/fail status along with reason for failure and list the number of vulns found

**Comment by ryancblack** [comment]
Need to discuss with PM and users if this functionality is desired from this tool. Thus far I don't think it's used much in the context of a command line tool, most of those end-users instead opting for a CI integration plugin, like Jenkins.

**Comment by ryancblack** [comment]
This is not required.
